name: couldai_user_app
description: "Aplicación de escritorio para monitoreo PYP y análisis de salud pública."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & State Management
  provider: ^6.1.1
  fl_chart: ^0.66.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  
  # Database & Storage
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  
  # Security & Utils
  crypto: ^3.0.3
  encrypt: ^5.0.3
  uuid: ^4.3.3
  device_info_plus: ^10.1.0
  
  # File Handling
  file_picker: ^8.0.0
  excel: ^4.0.0
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.16.0

flutter:
  uses-material-design: true
